name             "tig"
maintainer       "Mike King"
maintainer_email "mike@gir.pm"
license          "Apache 2.0"
description      "Install tig from homebrew"
version          "1.0.0"
supports         "mac_os_x"
depends          "homebrew"
