name             "Alfred 2"
maintainer       "Mike King"
maintainer_email "mike@gir.pm"
license          "Apache 2.0"
description      "Install Alfred 2"
version          "1.0.0"
supports         "mac_os_x"
depends          "zip_app"
